### ISSUE TITLE
Dotenv takes a long time when there is no .env file.

### ISSUE THREAD

**Issue by moimael** [motdotla/dotenv#169]
Hi,

We are using dotenv with an .env file in dev, and we use ENV variables for testing and production.

When launching our tests, we use this command: 

`node -r dotenv/config ./node_modules/.bin/jest`

Which results in the following in circle ci (they are way more warnings, I cut them by a lot):

```
{ Error: ENOENT: no such file or directory, open '.env'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.config (/home/ubuntu/galaxy/node_modules/dotenv/lib/main.js:30:37)
    at /home/ubuntu/galaxy/node_modules/dotenv/config.js:10:25
    at Object.<anonymous> (/home/ubuntu/galaxy/node_modules/dotenv/config.js:11:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12) errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
{ Error: ENOENT: no such file or directory, open '.env'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.config (/home/ubuntu/galaxy/node_modules/dotenv/lib/main.js:30:37)
    at /home/ubuntu/galaxy/node_modules/dotenv/config.js:10:25
    at Object.<anonymous> (/home/ubuntu/galaxy/node_modules/dotenv/config.js:11:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12) errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
{ Error: ENOENT: no such file or directory, open '.env'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.config (/home/ubuntu/galaxy/node_modules/dotenv/lib/main.js:30:37)
    at /home/ubuntu/galaxy/node_modules/dotenv/config.js:10:25
    at Object.<anonymous> (/home/ubuntu/galaxy/node_modules/dotenv/config.js:11:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12) errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
{ Error: ENOENT: no such file or directory, open '.env'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.config (/home/ubuntu/galaxy/node_modules/dotenv/lib/main.js:30:37)
    at /home/ubuntu/galaxy/node_modules/dotenv/config.js:10:25
    at Object.<anonymous> (/home/ubuntu/galaxy/node_modules/dotenv/config.js:11:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12) errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
{ Error: ENOENT: no such file or directory, open '.env'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.config (/home/ubuntu/galaxy/node_modules/dotenv/lib/main.js:30:37)
    at /home/ubuntu/galaxy/node_modules/dotenv/config.js:10:25
    at Object.<anonymous> (/home/ubuntu/galaxy/node_modules/dotenv/config.js:11:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12) errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
{ Error: ENOENT: no such file or directory, open '.env'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.config (/home/ubuntu/galaxy/node_modules/dotenv/lib/main.js:30:37)
    at /home/ubuntu/galaxy/node_modules/dotenv/config.js:10:25
    at Object.<anonymous> (/home/ubuntu/galaxy/node_modules/dotenv/config.js:11:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12) errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
```

The problem is those warning delays our tests from approximatelly 40 seconds. Is there any way to just ignore when there is no .env file, so it could work for dev, testing and production ?

Thanks.

**Comment by maxbeatty** [comment]
I'm not familiar with the internals of Jest, but I do know they run tests in parallel. If each test is trying to read a file from disk, that could explain the slow down. One thing you might try is touching an empty `.env` in your CI setup to see if `fs` is faster if it doesn't have to throw an error.

If there is someway dotenv could be faster, please open a PR with benchmarks 🏎

**Comment by moimael** [comment]
Thanks ! Touching a .env file silence the warnings but do not seems to speed up the tests (to be fair, I gain ~3 seconds).
