### ISSUE TITLE
Failing tests on Windows 7 Pro SP1

### ISSUE THREAD

**Issue by zenflow** [motdotla/dotenv#241]
Tried to set up this repo for development on my local machine yesterday and came across some apparent problems with portability:

```
C:\Users\mbrunetti\Documents\dotenv>npm test

> dotenv@4.0.0 pretest C:\Users\mbrunetti\Documents\dotenv
> npm run lint


> dotenv@4.0.0 lint C:\Users\mbrunetti\Documents\dotenv
> standard


> dotenv@4.0.0 postlint C:\Users\mbrunetti\Documents\dotenv
> npm run lint-md


> dotenv@4.0.0 lint-md C:\Users\mbrunetti\Documents\dotenv
> standard-markdown

Linting file 3 of 3


> dotenv@4.0.0 test C:\Users\mbrunetti\Documents\dotenv
> lab



  x..xx.x...............

Failed tests:

  1) config preload loads .env:

      Command failed: C:\Program Files\nodejs\node.exe -r ../config -e "console.log(process.env.BASIC)" dotenv_config_path=./test/.env
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.


  'C:\Program' is not recognized as an internal or external command,
  operable program or batch file.
  
      at ChildProcess.exithandler (child_process.js:275:12)
      at emitTwo (events.js:126:13)
      at ChildProcess.emit (events.js:214:7)
      at maybeClose (internal/child_process.js:925:16)
      at Socket.stream.socket.on (internal/child_process.js:346:11)
      at emitOne (events.js:116:13)
      at Socket.emit (events.js:211:7)
      at Pipe._handle.close [as _onclose] (net.js:554:12)

  4) dotenv config reads path with encoding, parsing output to process.env:

      actual expected

      01

      expected 0 to equal 1

      at Assertion.fail (C:\Users\mbrunetti\Documents\dotenv\node_modules\should\cjs\should.js:205:17)
      at Assertion.value (C:\Users\mbrunetti\Documents\dotenv\node_modules\should\cjs\should.js:277:19)
      at C:\Users\mbrunetti\Documents\dotenv\test\main.js:56:34
      at Immediate.setImmediate [as _onImmediate] (C:\Users\mbrunetti\Documents\dotenv\node_modules\lab\lib\runner.js:647:36)
      at runCallback (timers.js:789:20)
      at tryOnImmediate (timers.js:751:5)
      at processImmediate [as _immediateCallback] (timers.js:722:5)

  5) dotenv config makes load a synonym of config:

      actual expected

      01

      expected 0 to equal 1

      at Assertion.fail (C:\Users\mbrunetti\Documents\dotenv\node_modules\should\cjs\should.js:205:17)
      at Assertion.value (C:\Users\mbrunetti\Documents\dotenv\node_modules\should\cjs\should.js:277:19)
      at C:\Users\mbrunetti\Documents\dotenv\test\main.js:64:34
      at Immediate.setImmediate [as _onImmediate] (C:\Users\mbrunetti\Documents\dotenv\node_modules\lab\lib\runner.js:647:36)
      at runCallback (timers.js:789:20)
      at tryOnImmediate (timers.js:751:5)
      at processImmediate [as _immediateCallback] (timers.js:722:5)

  7) dotenv config does not write over keys already in process.env if the key has a falsy value:

      Cannot read property 'should' of undefined

      at C:\Users\mbrunetti\Documents\dotenv\test\main.js:82:24
      at Immediate.setImmediate [as _onImmediate] (C:\Users\mbrunetti\Documents\dotenv\node_modules\lab\lib\runner.js:647:36)
      at runCallback (timers.js:789:20)
      at tryOnImmediate (timers.js:751:5)
      at processImmediate [as _immediateCallback] (timers.js:722:5)


4 of 22 tests failed
Test duration: 46 ms
The following leaks were detected:WebAssembly

npm ERR! Test failed.  See above for more details.

```

1 is probably just a portability problem with the test

4 & 5 I have no idea, but it's the same problem.

7 looks like the feature doesn't work as expected on Windows

It will be great [when Travis CI supports Windows](https://github.com/travis-ci/travis-ci/milestone/5)

**Comment by maxbeatty** [comment]
Bummer that Travis CI doesn't yet support Windows. Are there other CI systems that offer Windows we can layer on to fix and test these issues?

**Comment by zenflow** [comment]
There's [AppVeyor](https://www.appveyor.com/), which I've seen used in combination with Travis, and is also free for open source projects

**Comment by maxbeatty** [comment]
@motdotla will you enable AppVeyor in order to test Windows? I added a basic config in #237

**Comment by zenflow** [comment]
@maxbeatty You will need to remove the `test/*` bit from the `npm test` script, since Windows command-line doesn't support globbing. You don't need to replace it with anything since (from the `lab` readme)

> By default, lab loads all the '*.js' files inside the local 'test' directory and executes the tests found. To use different directories or files, pass the file or directories as arguments

**Comment by zenflow** [comment]
The `-r lcov | coveralls` bit of that script was giving me problems too, for why I don't know

**Comment by maxbeatty** [comment]
I don't have a Windows machine to test on. Once AppVeyor is integrated, Pull Requests should report its status. At that point, it would be a big help to open a PR with fixes for the Windows environment (that also keep compatibility with everything to date)

**Comment by zenflow** [comment]
I'd be happy to open that PR. Should have time this weekend.

**Comment by zenflow** [comment]
I'll make this PR soon.. Probably tomorrow.

Is AppVeyor set up yet? I'm guessing I'll need to have 93df1db19503cddbe3a482637de6712e11bc045e cherry-picked into my branch for it to work when I open my PR

**Comment by maxbeatty** [comment]
@zenflow I have asked @motdotla to enable AppVeyor (I think he's the only one who can turn it on)

**Comment by zenflow** [comment]
Looks like AppVeyor is enabled now! (#260)

I will prepare the PR in the next couple of days.
