### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by Choxmi** [motdotla/dotenv#349]
It gives this error when using in Node (v4.2.6) and Express (3.5.2). Changing`let` to `val` will fix this issue.
This is the full trace : 
```
application/node_modules/dotenv/lib/main.js:45
      let value = keyValueArr[2] || ''
      ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (application/app.js:1:78)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

**Comment by maxbeatty** [comment]
[Support for Node v4 was dropped in v6](https://github.com/motdotla/dotenv/blob/master/CHANGELOG.md#changed). Using an earlier version of dotenv will resolve this
