### ISSUE TITLE
DotEnv creates a Socket file with the name of Port and Crashes the App

### ISSUE THREAD

**Issue by ashutosh4336** [motdotla/dotenv#455]
```
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 5000;
    at Server.setupListenHandle [as _listen2] (net.js:1292:21)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1456:5)
    at Function.listen (/home/ashutoshpanda/development/bootCampAPI/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/ashutoshpanda/development/bootCampAPI/server.js:11:5)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1336:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '5000;',
  port: -1
}
[nodemon] app crashed - waiting for file changes before starting...
^C
```

It says the port is already in use but it's not I've looked each Process with their PID but nothing is running on Port 5000.

![socket](https://user-images.githubusercontent.com/26510777/75845802-417ddd00-5e00-11ea-95e3-4123d70de6d8.png)

it Creates this file name 5000; and next time I try to run the application it crashes with the above Error Message.

**Comment by sukanta-manna** [comment]
BootcampAPI opens file using 
dotenv.config({ path: './config/config.env' }); 
not in conventional way 
require('dotenv').config({ path: '/custom/path/to/.env' });

**Comment by ashutosh4336** [comment]
Well I deleted the project (as I was just getting started then) and created new one with the same code and worked... But your way requires less code... I'll be using that from now... Thank you :)
