### ISSUE TITLE
ERROR: Unable to resolve module path  | ReactNative TS Template  | Apple Silicone (M1)

### ISSUE THREAD

**Issue by ImAbhishekTomar** [motdotla/dotenv#574]
The error is started when I am adding the below code. My Repo:  https://github.com/ImAbhishekTomar/RNRazorpay

```
import dotenv from 'dotenv';
dotenv.config();

OR

const dotenv = require('dotenv');

```

**Development Info**

react-native-cli: 2.0.1
react-native: 0.66.3
"@types/dotenv": "^8.2.0",
"dotenv": "^10.0.0",

**Error**

```
error: Error: Unable to resolve module path from /Users/abhishektomar/Desktop/root/apps/RNRazorpay/node_modules/dotenv/lib/main.js: path could not be found within the project or in these directories:
  node_modules
  ../node_modules

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
  10 |
  11 | type DotenvConfigOptions = {
> 12 |   path?: string, // path to .env file
     |                     ^
  13 |   encoding?: string, // encoding of .env file
  14 |   debug?: string // turn on logging for debugging purposes
  15 | }
    at ModuleResolver.resolveDependency (/Users/abhishektomar/Desktop/root/apps/RNRazorpay/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:129:15)
  at DependencyGraph.resolveDependency (/Users/abhishektomar/Desktop/root/apps/RNRazorpay/node_modules/metro/src/node-haste/DependencyGraph.js:288:43)
  at Object.resolve (/Users/abhishektomar/Desktop/root/apps/RNRazorpay/node_modules/metro/src/lib/transformHelpers.js:129:24)
  at resolve (/Users/abhishektomar/Desktop/root/apps/RNRazorpay/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
  at /Users/abhishektomar/Desktop/root/apps/RNRazorpay/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
  at Array.reduce (<anonymous>)
  at resolveDependencies (/Users/abhishektomar/Desktop/root/apps/RNRazorpay/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
  at processModule (/Users/abhishektomar/Desktop/root/apps/RNRazorpay/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
  at async addDependency (/Users/abhishektomar/Desktop/root/apps/RNRazorpay/node_modules/metro/src/DeltaBundler/traverseDependencies.js:230:18)
  at async Promise.all (index 1)

```

**Comment by boerdjamin** [comment]
same issue

**Comment by ImAbhishekTomar** [comment]
I have not found any solution yet.

**Comment by boerdjamin** [comment]
me neither. but I haven't tried anything further tbh

**Comment by ImAbhishekTomar** [comment]
anyone help on this?

**Comment by ImAbhishekTomar** [comment]
Alert: M1 is not ready for react developer, using for last 2 months and having a lot of issues.

**Comment by carlos3g** [comment]
I think dotenv doesn't supports react-native. See #268 and #125

**Comment by motdotla** [comment]
Putting this on our todo list. It would be nice if it supported react native out of the box.
