### ISSUE TITLE
mac m1 use rvm

### ISSUE THREAD

**Issue by xclidongbo** [motdotla/dotenv#717]
```
/Users/lidongbo/.rvm/gems/ruby-3.0.0/gems/dotenv-2.8.1/lib/dotenv/cli.rb:42:in `initialize': invalid option: -e (OptionParser::InvalidOption)
	from /Users/lidongbo/.rvm/gems/ruby-3.0.0/gems/dotenv-2.8.1/bin/dotenv:4:in `new'
	from /Users/lidongbo/.rvm/gems/ruby-3.0.0/gems/dotenv-2.8.1/bin/dotenv:4:in `<top (required)>'
	from /Users/lidongbo/.rvm/gems/ruby-3.0.0/bin/dotenv:23:in `load'
	from /Users/lidongbo/.rvm/gems/ruby-3.0.0/bin/dotenv:23:in `<main>'
/Users/lidongbo/.rvm/gems/ruby-3.0.0/gems/dotenv-2.8.1/lib/dotenv/cli.rb:42:in `initialize': invalid option: e 

```

**Comment by motdotla** [comment]
This is the node dotenv repo. Please publish this to the ruby dotenv repo.
